### ISSUE TITLE
kaolin installation problem

### ISSUE THREAD

**Issue by bobfacer** [zju3dv/NeuralRecon-W#17]
The kaolin install needs pytorch<=1.7.0,see [https://kaolin.readthedocs.io/en/v0.9.1/notes/installation.html](url),but the code seems not work in pytorch==1.7.0,how to solve this conflict?I run `scripts/data_generation.sh data/brandenburg_gate`,
when i use pytorch==1.7.0,it has the following error：
`Traceback (most recent call last):
  File "tools/prepare_data/prepare_data_cache.py", line 176, in <module>
    dataset = dataset_dict[args.dataset_name](**kwargs)
  File "/root/NeuralRecon-W/./datasets/phototourism.py", line 123, in __init__
    self.read_meta()
  File "/root/NeuralRecon-W/./datasets/phototourism.py", line 576, in read_meta
    depth_sfm, weight = self.get_colmap_depth(
  File "/root/NeuralRecon-W/./datasets/phototourism.py", line 199, in get_colmap_depth
    extrinsic = torch.linalg.inv(pose)
AttributeError: module 'torch.linalg' has no attribute 'inv'`
when i use pytorch==1.8.0,i can not install kaolin successfully,it give the following error:
`Traceback (most recent call last):
  File "tools/prepare_data/prepare_data_cache.py", line 5, in <module>
    from datasets import dataset_dict
  File "/root/NeuralRecon-W/./datasets/__init__.py", line 1, in <module>
    from .phototourism import PhototourismDataset
  File "/root/NeuralRecon-W/./datasets/phototourism.py", line 16, in <module>
    from tools.prepare_data.generate_voxel import get_near_far, gen_octree_from_sfm
  File "/root/NeuralRecon-W/./tools/prepare_data/generate_voxel.py", line 13, in <module>
    from kaolin.ops import spc
  File "/root/NeuralRecon-W/kaolin/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/root/NeuralRecon-W/kaolin/kaolin/io/__init__.py", line 5, in <module>
    from . import render
  File "/root/NeuralRecon-W/kaolin/kaolin/io/render.py", line 23, in <module>
    from ..render.camera import generate_perspective_projection
  File "/root/NeuralRecon-W/kaolin/kaolin/render/__init__.py", line 2, in <module>
    from . import mesh
  File "/root/NeuralRecon-W/kaolin/kaolin/render/mesh/__init__.py", line 1, in <module>
    from .utils import *
  File "/root/NeuralRecon-W/kaolin/kaolin/render/mesh/utils.py", line 22, in <module>
    from ... import ops
  File "/root/NeuralRecon-W/kaolin/kaolin/ops/__init__.py", line 1, in <module>
    from . import batch
  File "/root/NeuralRecon-W/kaolin/kaolin/ops/batch.py", line 17, in <module>
    from kaolin import _C
ImportError: /root/NeuralRecon-W/kaolin/kaolin/_C.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv`

**Comment by lulianLiu** [comment]
I have the same problems? Do you solve it?

**Comment by lulianLiu** [comment]
> The kaolin install needs pytorch<=1.7.0,see [https://kaolin.readthedocs.io/en/v0.9.1/notes/installation.html](url),but the code seems not work in pytorch==1.7.0,how to solve this conflict?I run `scripts/data_generation.sh data/brandenburg_gate`, when i use pytorch==1.7.0,it has the following error： `Traceback (most recent call last): File "tools/prepare_data/prepare_data_cache.py", line 176, in <module> dataset = dataset_dict[args.dataset_name](**kwargs) File "/root/NeuralRecon-W/./datasets/phototourism.py", line 123, in __init__ self.read_meta() File "/root/NeuralRecon-W/./datasets/phototourism.py", line 576, in read_meta depth_sfm, weight = self.get_colmap_depth( File "/root/NeuralRecon-W/./datasets/phototourism.py", line 199, in get_colmap_depth extrinsic = torch.linalg.inv(pose) AttributeError: module 'torch.linalg' has no attribute 'inv'` when i use pytorch==1.8.0,i can not install kaolin successfully,it give the following error: `Traceback (most recent call last): File "tools/prepare_data/prepare_data_cache.py", line 5, in <module> from datasets import dataset_dict File "/root/NeuralRecon-W/./datasets/__init__.py", line 1, in <module> from .phototourism import PhototourismDataset File "/root/NeuralRecon-W/./datasets/phototourism.py", line 16, in <module> from tools.prepare_data.generate_voxel import get_near_far, gen_octree_from_sfm File "/root/NeuralRecon-W/./tools/prepare_data/generate_voxel.py", line 13, in <module> from kaolin.ops import spc File "/root/NeuralRecon-W/kaolin/kaolin/__init__.py", line 1, in <module> from . import io File "/root/NeuralRecon-W/kaolin/kaolin/io/__init__.py", line 5, in <module> from . import render File "/root/NeuralRecon-W/kaolin/kaolin/io/render.py", line 23, in <module> from ..render.camera import generate_perspective_projection File "/root/NeuralRecon-W/kaolin/kaolin/render/__init__.py", line 2, in <module> from . import mesh File "/root/NeuralRecon-W/kaolin/kaolin/render/mesh/__init__.py", line 1, in <module> from .utils import * File "/root/NeuralRecon-W/kaolin/kaolin/render/mesh/utils.py", line 22, in <module> from ... import ops File "/root/NeuralRecon-W/kaolin/kaolin/ops/__init__.py", line 1, in <module> from . import batch File "/root/NeuralRecon-W/kaolin/kaolin/ops/batch.py", line 17, in <module> from kaolin import _C ImportError: /root/NeuralRecon-W/kaolin/kaolin/_C.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv`

I have the same problems? Do you solve it?
